//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetaSabaPortal.Resources.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetaSabaPortal.Resources.Locales.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _Button_ConfirmCancel {
            get {
                return ResourceManager.GetString("_Button_ConfirmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string _Button_ConfirmOk {
            get {
                return ResourceManager.GetString("_Button_ConfirmOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Detect.
        /// </summary>
        internal static string _ButtonAuto_Caption {
            get {
                return ResourceManager.GetString("_ButtonAuto_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string _ButtonBrowse_Caption {
            get {
                return ResourceManager.GetString("_ButtonBrowse_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract.
        /// </summary>
        internal static string _ButtonExtract_Caption {
            get {
                return ResourceManager.GetString("_ButtonExtract_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string _ProgressLabel {
            get {
                return ResourceManager.GetString("_ProgressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US East Coast.
        /// </summary>
        internal static string _RegionItems_0 {
            get {
                return ResourceManager.GetString("_RegionItems_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US West Coast.
        /// </summary>
        internal static string _RegionItems_1 {
            get {
                return ResourceManager.GetString("_RegionItems_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South America.
        /// </summary>
        internal static string _RegionItems_2 {
            get {
                return ResourceManager.GetString("_RegionItems_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest of the world.
        /// </summary>
        internal static string _RegionItems_255 {
            get {
                return ResourceManager.GetString("_RegionItems_255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe.
        /// </summary>
        internal static string _RegionItems_3 {
            get {
                return ResourceManager.GetString("_RegionItems_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia.
        /// </summary>
        internal static string _RegionItems_4 {
            get {
                return ResourceManager.GetString("_RegionItems_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia.
        /// </summary>
        internal static string _RegionItems_5 {
            get {
                return ResourceManager.GetString("_RegionItems_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle East.
        /// </summary>
        internal static string _RegionItems_6 {
            get {
                return ResourceManager.GetString("_RegionItems_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Africa.
        /// </summary>
        internal static string _RegionItems_7 {
            get {
                return ResourceManager.GetString("_RegionItems_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string _TabAbout_Caption {
            get {
                return ResourceManager.GetString("_TabAbout_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatorTool.
        /// </summary>
        internal static string _TabCreator_Caption {
            get {
                return ResourceManager.GetString("_TabCreator_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unarchive.
        /// </summary>
        internal static string _TabExtract_Caption {
            get {
                return ResourceManager.GetString("_TabExtract_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string _TabSettings_Caption {
            get {
                return ResourceManager.GetString("_TabSettings_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watcher.
        /// </summary>
        internal static string _TabWatcher_Caption {
            get {
                return ResourceManager.GetString("_TabWatcher_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published Date:.
        /// </summary>
        internal static string ExtractingTab_ConfirmDateLabel {
            get {
                return ResourceManager.GetString("ExtractingTab_ConfirmDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to proceed?.
        /// </summary>
        internal static string ExtractingTab_ConfirmMainLabel {
            get {
                return ResourceManager.GetString("ExtractingTab_ConfirmMainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string ExtractingTab_ConfirmTitleLabel {
            get {
                return ResourceManager.GetString("ExtractingTab_ConfirmTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Cannot find the real root directory of CS2. Perhaps the CS2 update has changed the folder structure, or your game folder has been replaced through means such as HardLink?.
        /// </summary>
        internal static string ExtractingTab_Msg_Cs2ActualRootDirNotFoundError {
            get {
                return ResourceManager.GetString("ExtractingTab_Msg_Cs2ActualRootDirNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CS2 Client path not specified..
        /// </summary>
        internal static string ExtractingTab_Msg_Cs2PathEmpty {
            get {
                return ResourceManager.GetString("ExtractingTab_Msg_Cs2PathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item has been selected yet, please select one first..
        /// </summary>
        internal static string ExtractingTab_Msg_NoEntitySelected {
            get {
                return ResourceManager.GetString("ExtractingTab_Msg_NoEntitySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Client path not specified..
        /// </summary>
        internal static string ExtractingTab_Msg_SteamPathEmpty {
            get {
                return ResourceManager.GetString("ExtractingTab_Msg_SteamPathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Vpk file not found. Perhaps the Steam Workshop item has not been subscribed to? Or Steam has not been initiated to download the subscribed item?.
        /// </summary>
        internal static string ExtractingTab_Msg_VpkNotFoundError {
            get {
                return ResourceManager.GetString("ExtractingTab_Msg_VpkNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting finished..
        /// </summary>
        internal static string ExtractingTab_Msg_WorkFinished {
            get {
                return ResourceManager.GetString("ExtractingTab_Msg_WorkFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CS2 Workshop ACF file&apos;s path not specified..
        /// </summary>
        internal static string ExtractingTab_Msg_WorkshopAcfPathEmpty {
            get {
                return ResourceManager.GetString("ExtractingTab_Msg_WorkshopAcfPathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting....
        /// </summary>
        internal static string ExtractingTab_Msg_WorkStarted {
            get {
                return ResourceManager.GetString("ExtractingTab_Msg_WorkStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CS2 Client Installation Folder not found. Please select manually..
        /// </summary>
        internal static string SettingsTab_Msg_AutoCs2NotFound {
            get {
                return ResourceManager.GetString("SettingsTab_Msg_AutoCs2NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Client Installation Folder not found. Please select manually..
        /// </summary>
        internal static string SettingsTab_Msg_AutoSteamNotFound {
            get {
                return ResourceManager.GetString("SettingsTab_Msg_AutoSteamNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;appworkshop_730.acf&quot; not found. Please select manually..
        /// </summary>
        internal static string SettingsTab_Msg_AutoWorkshopAcfNotFound {
            get {
                return ResourceManager.GetString("SettingsTab_Msg_AutoWorkshopAcfNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to .
        /// </summary>
        internal static string TabSettings_Cs2AcfPathLabel_0 {
            get {
                return ResourceManager.GetString("TabSettings_Cs2AcfPathLabel_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appworkshop_730.acf.
        /// </summary>
        internal static string TabSettings_Cs2AcfPathLabel_1 {
            get {
                return ResourceManager.GetString("TabSettings_Cs2AcfPathLabel_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (CS2 Workshop File):.
        /// </summary>
        internal static string TabSettings_Cs2AcfPathLabel_2 {
            get {
                return ResourceManager.GetString("TabSettings_Cs2AcfPathLabel_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to .
        /// </summary>
        internal static string TabSettings_Cs2PathLabel_0 {
            get {
                return ResourceManager.GetString("TabSettings_Cs2PathLabel_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cs2.exe.
        /// </summary>
        internal static string TabSettings_Cs2PathLabel_1 {
            get {
                return ResourceManager.GetString("TabSettings_Cs2PathLabel_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (You can also select .
        /// </summary>
        internal static string TabSettings_Cs2PathLabel_2 {
            get {
                return ResourceManager.GetString("TabSettings_Cs2PathLabel_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to csgo.exe.
        /// </summary>
        internal static string TabSettings_Cs2PathLabel_3 {
            get {
                return ResourceManager.GetString("TabSettings_Cs2PathLabel_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ):.
        /// </summary>
        internal static string TabSettings_Cs2PathLabel_4 {
            get {
                return ResourceManager.GetString("TabSettings_Cs2PathLabel_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved..
        /// </summary>
        internal static string TabSettings_Msg_SettingsSaved {
            get {
                return ResourceManager.GetString("TabSettings_Msg_SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to .
        /// </summary>
        internal static string TabSettings_SteamPathLabel_0 {
            get {
                return ResourceManager.GetString("TabSettings_SteamPathLabel_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steam.exe.
        /// </summary>
        internal static string TabSettings_SteamPathLabel_1 {
            get {
                return ResourceManager.GetString("TabSettings_SteamPathLabel_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string TabSettings_SteamPathLabel_2 {
            get {
                return ResourceManager.GetString("TabSettings_SteamPathLabel_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update List.
        /// </summary>
        internal static string TabUnarchive_UpdateList_Button {
            get {
                return ResourceManager.GetString("TabUnarchive_UpdateList_Button", resourceCulture);
            }
        }
    }
}
