//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetaSabaPortal.Resources.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetaSabaPortal.Resources.Locales.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Detect.
        /// </summary>
        internal static string _ButtonAuto_Caption {
            get {
                return ResourceManager.GetString("_ButtonAuto_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string _ButtonBrowse_Caption {
            get {
                return ResourceManager.GetString("_ButtonBrowse_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract.
        /// </summary>
        internal static string _ButtonExtract_Caption {
            get {
                return ResourceManager.GetString("_ButtonExtract_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string _ProgressLabel {
            get {
                return ResourceManager.GetString("_ProgressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string _TabAbout_Caption {
            get {
                return ResourceManager.GetString("_TabAbout_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unarchive.
        /// </summary>
        internal static string _TabExtract_Caption {
            get {
                return ResourceManager.GetString("_TabExtract_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string _TabSettings_Caption {
            get {
                return ResourceManager.GetString("_TabSettings_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting finished..
        /// </summary>
        internal static string ExtractingTab_Msg_WorkFinished {
            get {
                return ResourceManager.GetString("ExtractingTab_Msg_WorkFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting....
        /// </summary>
        internal static string ExtractingTab_Msg_WorkStarted {
            get {
                return ResourceManager.GetString("ExtractingTab_Msg_WorkStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to .
        /// </summary>
        internal static string TabSettings_Cs2AcfPathLabel_0 {
            get {
                return ResourceManager.GetString("TabSettings_Cs2AcfPathLabel_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appmanifest_730.acf.
        /// </summary>
        internal static string TabSettings_Cs2AcfPathLabel_1 {
            get {
                return ResourceManager.GetString("TabSettings_Cs2AcfPathLabel_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (CS2 Workshop File):.
        /// </summary>
        internal static string TabSettings_Cs2AcfPathLabel_2 {
            get {
                return ResourceManager.GetString("TabSettings_Cs2AcfPathLabel_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to .
        /// </summary>
        internal static string TabSettings_Cs2PathLabel_0 {
            get {
                return ResourceManager.GetString("TabSettings_Cs2PathLabel_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cs2.exe.
        /// </summary>
        internal static string TabSettings_Cs2PathLabel_1 {
            get {
                return ResourceManager.GetString("TabSettings_Cs2PathLabel_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (You can also select .
        /// </summary>
        internal static string TabSettings_Cs2PathLabel_2 {
            get {
                return ResourceManager.GetString("TabSettings_Cs2PathLabel_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to csgo.exe.
        /// </summary>
        internal static string TabSettings_Cs2PathLabel_3 {
            get {
                return ResourceManager.GetString("TabSettings_Cs2PathLabel_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ):.
        /// </summary>
        internal static string TabSettings_Cs2PathLabel_4 {
            get {
                return ResourceManager.GetString("TabSettings_Cs2PathLabel_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to .
        /// </summary>
        internal static string TabSettings_SteamPathLabel_0 {
            get {
                return ResourceManager.GetString("TabSettings_SteamPathLabel_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steam.exe.
        /// </summary>
        internal static string TabSettings_SteamPathLabel_1 {
            get {
                return ResourceManager.GetString("TabSettings_SteamPathLabel_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string TabSettings_SteamPathLabel_2 {
            get {
                return ResourceManager.GetString("TabSettings_SteamPathLabel_2", resourceCulture);
            }
        }
    }
}
